name: Windows


on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Check Version
      shell: cmd
      run: cmake --version
    
    - name: Build
      shell: cmd
      run: build-default.bat
    - name: Archieve Artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
         name: windows
         path: |
          win-BIN-Win32
          win-BIN-x64
